# Generated by Django 3.0.6 on 2020-05-10 20:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_name', models.CharField(max_length=120)),
                ('tz', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='activity_period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=datetime.datetime(2020, 5, 11, 1, 51, 33, 808342))),
                ('end_time', models.DateTimeField(default=datetime.datetime(2020, 5, 11, 1, 51, 33, 808342))),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.member')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
    ]
