# Generated by Django 3.0.6 on 2020-05-10 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0003_auto_20200511_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity_period',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='activity_period',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
