# Generated by Django 3.0.6 on 2020-05-10 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0004_auto_20200511_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity_period',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quickstart.member'),
        ),
    ]
