# Generated by Django 3.0.6 on 2020-05-10 19:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='activity_period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=datetime.datetime(2020, 5, 11, 1, 3, 48, 220407))),
                ('end_time', models.DateTimeField(default=datetime.datetime(2020, 5, 11, 1, 3, 48, 220407))),
            ],
        ),
        migrations.CreateModel(
            name='member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_name', models.CharField(max_length=120)),
                ('tz', models.PositiveIntegerField()),
            ],
        ),
    ]
