# Generated by Django 3.0.6 on 2020-05-10 19:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity_period',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 11, 1, 9, 33, 541921)),
        ),
        migrations.AlterField(
            model_name='activity_period',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 11, 1, 9, 33, 541921)),
        ),
        migrations.AlterField(
            model_name='member',
            name='tz',
            field=models.CharField(max_length=120),
        ),
    ]
