# Generated by Django 3.0.6 on 2020-05-10 20:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0003_auto_20200511_0139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity_period',
            old_name='memberss',
            new_name='member',
        ),
        migrations.AlterField(
            model_name='activity_period',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 11, 1, 44, 35, 410175)),
        ),
        migrations.AlterField(
            model_name='activity_period',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 11, 1, 44, 35, 410175)),
        ),
    ]
